# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: go.chromium.org/luci/vpython/api/vpython/env.proto
"""Generated protocol buffer code."""
from chromite.third_party.google.protobuf import descriptor as _descriptor
from chromite.third_party.google.protobuf import message as _message
from chromite.third_party.google.protobuf import reflection as _reflection
from chromite.third_party.google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_test.go.chromium.org.luci.vpython.api.vpython import pep425_pb2 as go_dot_chromium_dot_org_dot_luci_dot_vpython_dot_api_dot_vpython_dot_pep425__pb2
from chromite.api.gen_test.go.chromium.org.luci.vpython.api.vpython import spec_pb2 as go_dot_chromium_dot_org_dot_luci_dot_vpython_dot_api_dot_vpython_dot_spec__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='go.chromium.org/luci/vpython/api/vpython/env.proto',
  package='vpython',
  syntax='proto3',
  serialized_options=b'Z(go.chromium.org/luci/vpython/api/vpython',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n2go.chromium.org/luci/vpython/api/vpython/env.proto\x12\x07vpython\x1a\x35go.chromium.org/luci/vpython/api/vpython/pep425.proto\x1a\x33go.chromium.org/luci/vpython/api/vpython/spec.proto\"u\n\x0b\x45nvironment\x12\x1b\n\x04spec\x18\x01 \x01(\x0b\x32\r.vpython.Spec\x12!\n\x07runtime\x18\x02 \x01(\x0b\x32\x10.vpython.Runtime\x12&\n\npep425_tag\x18\x03 \x03(\x0b\x32\x12.vpython.PEP425Tag\"T\n\x07Runtime\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04hash\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0e\n\x06prefix\x18\x04 \x01(\t\x12\x0c\n\x04\x61rch\x18\x05 \x01(\tB*Z(go.chromium.org/luci/vpython/api/vpythonb\x06proto3'
  ,
  dependencies=[go_dot_chromium_dot_org_dot_luci_dot_vpython_dot_api_dot_vpython_dot_pep425__pb2.DESCRIPTOR,go_dot_chromium_dot_org_dot_luci_dot_vpython_dot_api_dot_vpython_dot_spec__pb2.DESCRIPTOR,])




_ENVIRONMENT = _descriptor.Descriptor(
  name='Environment',
  full_name='vpython.Environment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='spec', full_name='vpython.Environment.spec', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='runtime', full_name='vpython.Environment.runtime', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pep425_tag', full_name='vpython.Environment.pep425_tag', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=288,
)


_RUNTIME = _descriptor.Descriptor(
  name='Runtime',
  full_name='vpython.Runtime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='vpython.Runtime.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hash', full_name='vpython.Runtime.hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='vpython.Runtime.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prefix', full_name='vpython.Runtime.prefix', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arch', full_name='vpython.Runtime.arch', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=374,
)

_ENVIRONMENT.fields_by_name['spec'].message_type = go_dot_chromium_dot_org_dot_luci_dot_vpython_dot_api_dot_vpython_dot_spec__pb2._SPEC
_ENVIRONMENT.fields_by_name['runtime'].message_type = _RUNTIME
_ENVIRONMENT.fields_by_name['pep425_tag'].message_type = go_dot_chromium_dot_org_dot_luci_dot_vpython_dot_api_dot_vpython_dot_pep425__pb2._PEP425TAG
DESCRIPTOR.message_types_by_name['Environment'] = _ENVIRONMENT
DESCRIPTOR.message_types_by_name['Runtime'] = _RUNTIME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Environment = _reflection.GeneratedProtocolMessageType('Environment', (_message.Message,), {
  'DESCRIPTOR' : _ENVIRONMENT,
  '__module__' : 'go.chromium.org.luci.vpython.api.vpython.env_pb2'
  # @@protoc_insertion_point(class_scope:vpython.Environment)
  })
_sym_db.RegisterMessage(Environment)

Runtime = _reflection.GeneratedProtocolMessageType('Runtime', (_message.Message,), {
  'DESCRIPTOR' : _RUNTIME,
  '__module__' : 'go.chromium.org.luci.vpython.api.vpython.env_pb2'
  # @@protoc_insertion_point(class_scope:vpython.Runtime)
  })
_sym_db.RegisterMessage(Runtime)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
