# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: go.chromium.org/luci/vpython/api/vpython/pep425.proto
"""Generated protocol buffer code."""
from chromite.third_party.google.protobuf import descriptor as _descriptor
from chromite.third_party.google.protobuf import message as _message
from chromite.third_party.google.protobuf import reflection as _reflection
from chromite.third_party.google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='go.chromium.org/luci/vpython/api/vpython/pep425.proto',
  package='vpython',
  syntax='proto3',
  serialized_options=b'Z(go.chromium.org/luci/vpython/api/vpython',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n5go.chromium.org/luci/vpython/api/vpython/pep425.proto\x12\x07vpython\":\n\tPEP425Tag\x12\x0e\n\x06python\x18\x01 \x01(\t\x12\x0b\n\x03\x61\x62i\x18\x02 \x01(\t\x12\x10\n\x08platform\x18\x03 \x01(\tB*Z(go.chromium.org/luci/vpython/api/vpythonb\x06proto3'
)




_PEP425TAG = _descriptor.Descriptor(
  name='PEP425Tag',
  full_name='vpython.PEP425Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='python', full_name='vpython.PEP425Tag.python', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='abi', full_name='vpython.PEP425Tag.abi', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='platform', full_name='vpython.PEP425Tag.platform', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['PEP425Tag'] = _PEP425TAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PEP425Tag = _reflection.GeneratedProtocolMessageType('PEP425Tag', (_message.Message,), {
  'DESCRIPTOR' : _PEP425TAG,
  '__module__' : 'go.chromium.org.luci.vpython.api.vpython.pep425_pb2'
  # @@protoc_insertion_point(class_scope:vpython.PEP425Tag)
  })
_sym_db.RegisterMessage(PEP425Tag)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
