# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/lab/api/bluetooth_peer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,chromiumos/test/lab/api/bluetooth_peer.proto\x12\x17\x63hromiumos.test.lab.api\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x02\n\x1d\x42luetoothPeerChameleondConfig\x12\x1e\n\x16next_chameleond_commit\x18\x01 \x01(\t\x12\x16\n\x0enext_dut_hosts\x18\x02 \x03(\t\x12!\n\x19next_dut_release_versions\x18\x03 \x03(\t\x12X\n\x07\x62undles\x18\x04 \x03(\x0b\x32G.chromiumos.test.lab.api.BluetoothPeerChameleondConfig.ChameleondBundle\x1a\x64\n\x10\x43hameleondBundle\x12\x19\n\x11\x63hameleond_commit\x18\x01 \x01(\t\x12\x14\n\x0c\x61rchive_path\x18\x02 \x01(\t\x12\x1f\n\x17min_dut_release_version\x18\x03 \x01(\t\"\xf3\x01\n\x1cRaspiosCrosBtpeerImageConfig\x12\x1a\n\x12\x63urrent_image_uuid\x18\x01 \x01(\t\x12\x17\n\x0fnext_image_uuid\x18\x02 \x01(\t\x12(\n next_image_verification_dut_pool\x18\x03 \x03(\t\x12M\n\x06images\x18\x04 \x03(\x0b\x32=.chromiumos.test.lab.api.RaspiosCrosBtpeerImageConfig.OSImage\x1a%\n\x07OSImage\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"\xf3\x01\n\x1fRaspiosCrosBtpeerImageBuildInfo\x12\x12\n\nimage_uuid\x18\x01 \x01(\t\x12\x34\n\x10image_build_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12V\n\x07sources\x18\x03 \x03(\x0b\x32\x45.chromiumos.test.lab.api.RaspiosCrosBtpeerImageBuildInfo.SourcesEntry\x1a.\n\x0cSourcesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x33Z1go.chromium.org/chromiumos/config/go/test/lab/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.test.lab.api.bluetooth_peer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1go.chromium.org/chromiumos/config/go/test/lab/api'
  _RASPIOSCROSBTPEERIMAGEBUILDINFO_SOURCESENTRY._options = None
  _RASPIOSCROSBTPEERIMAGEBUILDINFO_SOURCESENTRY._serialized_options = b'8\001'
  _globals['_BLUETOOTHPEERCHAMELEONDCONFIG']._serialized_start=107
  _globals['_BLUETOOTHPEERCHAMELEONDCONFIG']._serialized_end=421
  _globals['_BLUETOOTHPEERCHAMELEONDCONFIG_CHAMELEONDBUNDLE']._serialized_start=321
  _globals['_BLUETOOTHPEERCHAMELEONDCONFIG_CHAMELEONDBUNDLE']._serialized_end=421
  _globals['_RASPIOSCROSBTPEERIMAGECONFIG']._serialized_start=424
  _globals['_RASPIOSCROSBTPEERIMAGECONFIG']._serialized_end=667
  _globals['_RASPIOSCROSBTPEERIMAGECONFIG_OSIMAGE']._serialized_start=630
  _globals['_RASPIOSCROSBTPEERIMAGECONFIG_OSIMAGE']._serialized_end=667
  _globals['_RASPIOSCROSBTPEERIMAGEBUILDINFO']._serialized_start=670
  _globals['_RASPIOSCROSBTPEERIMAGEBUILDINFO']._serialized_end=913
  _globals['_RASPIOSCROSBTPEERIMAGEBUILDINFO_SOURCESENTRY']._serialized_start=867
  _globals['_RASPIOSCROSBTPEERIMAGEBUILDINFO_SOURCESENTRY']._serialized_end=913
# @@protoc_insertion_point(module_scope)
