# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/lab/api/dut_action_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromiumos.test.lab.api import rpm_pb2 as chromiumos_dot_test_dot_lab_dot_api_dot_rpm__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0chromiumos/test/lab/api/dut_action_service.proto\x12\x17\x63hromiumos.test.lab.api\x1a!chromiumos/test/lab/api/rpm.proto\"\xc8\x01\n\x17SetRpmPowerStateRequest\x12\x1a\n\x12powerunit_hostname\x18\x01 \x01(\t\x12\x18\n\x10powerunit_outlet\x18\x02 \x01(\t\x12\x35\n\x05state\x18\x03 \x01(\x0e\x32&.chromiumos.test.lab.api.RpmPowerState\x12.\n\x04type\x18\x04 \x01(\x0e\x32 .chromiumos.test.lab.api.RPMType\x12\x10\n\x08\x64ut_name\x18\x05 \x01(\t\"Q\n\x18SetRpmPowerStateResponse\x12\x35\n\x05state\x18\x01 \x01(\x0e\x32&.chromiumos.test.lab.api.RpmPowerState*|\n\rRpmPowerState\x12\x1f\n\x1bRPM_POWER_STATE_UNSPECIFIED\x10\x00\x12\x16\n\x12RPM_POWER_STATE_ON\x10\x01\x12\x17\n\x13RPM_POWER_STATE_OFF\x10\x02\x12\x19\n\x15RPM_POWER_STATE_CYCLE\x10\x03\x32\x8b\x01\n\x10\x44utActionService\x12w\n\x10SetRpmPowerState\x12\x30.chromiumos.test.lab.api.SetRpmPowerStateRequest\x1a\x31.chromiumos.test.lab.api.SetRpmPowerStateResponseB3Z1go.chromium.org/chromiumos/config/go/test/lab/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.test.lab.api.dut_action_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1go.chromium.org/chromiumos/config/go/test/lab/api'
  _globals['_RPMPOWERSTATE']._serialized_start=398
  _globals['_RPMPOWERSTATE']._serialized_end=522
  _globals['_SETRPMPOWERSTATEREQUEST']._serialized_start=113
  _globals['_SETRPMPOWERSTATEREQUEST']._serialized_end=313
  _globals['_SETRPMPOWERSTATERESPONSE']._serialized_start=315
  _globals['_SETRPMPOWERSTATERESPONSE']._serialized_end=396
  _globals['_DUTACTIONSERVICE']._serialized_start=525
  _globals['_DUTACTIONSERVICE']._serialized_end=664
# @@protoc_insertion_point(module_scope)
