# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/lab/api/dut_provision_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromiumos.test.lab.api import provision_attempt_pb2 as chromiumos_dot_test_dot_lab_dot_api_dot_provision__attempt__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3chromiumos/test/lab/api/dut_provision_service.proto\x12\x17\x63hromiumos.test.lab.api\x1a/chromiumos/test/lab/api/provision_attempt.proto\"b\n\x1dUploadProvisionMetricsRequest\x12\x41\n\x08\x61ttempts\x18\x01 \x03(\x0b\x32/.chromiumos.test.lab.api.ProvisionAttemptRecord\" \n\x1eUploadProvisionMetricsResponse2\xa1\x01\n\x13\x44utProvisionService\x12\x89\x01\n\x16UploadProvisionMetrics\x12\x36.chromiumos.test.lab.api.UploadProvisionMetricsRequest\x1a\x37.chromiumos.test.lab.api.UploadProvisionMetricsResponseB3Z1go.chromium.org/chromiumos/config/go/test/lab/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.test.lab.api.dut_provision_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1go.chromium.org/chromiumos/config/go/test/lab/api'
  _globals['_UPLOADPROVISIONMETRICSREQUEST']._serialized_start=129
  _globals['_UPLOADPROVISIONMETRICSREQUEST']._serialized_end=227
  _globals['_UPLOADPROVISIONMETRICSRESPONSE']._serialized_start=229
  _globals['_UPLOADPROVISIONMETRICSRESPONSE']._serialized_end=261
  _globals['_DUTPROVISIONSERVICE']._serialized_start=264
  _globals['_DUTPROVISIONSERVICE']._serialized_end=425
# @@protoc_insertion_point(module_scope)
