# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/lab/api/pasit_host.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromiumos.test.lab.api import rpm_pb2 as chromiumos_dot_test_dot_lab_dot_api_dot_rpm__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(chromiumos/test/lab/api/pasit_host.proto\x12\x17\x63hromiumos.test.lab.api\x1a!chromiumos/test/lab/api/rpm.proto\"\xd7\x07\n\tPasitHost\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12:\n\x07\x64\x65vices\x18\x02 \x03(\x0b\x32).chromiumos.test.lab.api.PasitHost.Device\x12\x42\n\x0b\x63onnections\x18\x03 \x03(\x0b\x32-.chromiumos.test.lab.api.PasitHost.Connection\x1aq\n\nConnection\x12\x13\n\x0bparent_port\x18\x01 \x01(\t\x12\x11\n\tparent_id\x18\x02 \x01(\t\x12\x10\n\x08\x63hild_id\x18\x03 \x01(\t\x12\r\n\x05speed\x18\x04 \x01(\x02\x12\x0c\n\x04type\x18\x05 \x01(\t\x12\x0c\n\x04tags\x18\x06 \x03(\t\x1a\xc4\x05\n\x06\x44\x65vice\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12<\n\x04type\x18\x03 \x01(\x0e\x32..chromiumos.test.lab.api.PasitHost.Device.Type\x12K\n\x0cpower_supply\x18\x04 \x01(\x0b\x32\x35.chromiumos.test.lab.api.PasitHost.Device.PowerSupply\x12)\n\x03rpm\x18\x05 \x01(\x0b\x32\x1c.chromiumos.test.lab.api.RPM\x12`\n\x16switch_fixture_details\x18\x06 \x01(\x0b\x32>.chromiumos.test.lab.api.PasitHost.Device.SwitchFixtureDetailsH\x00\x12\x18\n\x10observing_camera\x18\x07 \x01(\t\x1a>\n\x0bPowerSupply\x12\x0f\n\x07\x63urrent\x18\x01 \x01(\x02\x12\x0f\n\x07voltage\x18\x02 \x01(\x02\x12\r\n\x05power\x18\x03 \x01(\x02\x1aK\n\x14SwitchFixtureDetails\x12\x1d\n\x15initial_state_enabled\x18\x01 \x01(\x08\x12\x14\n\x0cinitial_port\x18\x02 \x01(\t\"\xcd\x01\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03\x44UT\x10\x01\x12\x12\n\x0eSWITCH_FIXTURE\x10\x02\x12\x13\n\x0f\x44OCKING_STATION\x10\x03\x12\x0b\n\x07MONITOR\x10\x04\x12\n\n\x06\x43\x41MERA\x10\x05\x12\x0b\n\x07STORAGE\x10\x06\x12\x07\n\x03HID\x10\x07\x12\x0b\n\x07NETWORK\x10\x08\x12\r\n\tHEADPHONE\x10\t\x12\x0b\n\x07SPEAKER\x10\n\x12\x0c\n\x08IP_POWER\x10\x0b\x12\x0e\n\nUSB_TESTER\x10\x0c\x12\x10\n\x0cVIDEO_TESTER\x10\rB\x10\n\x0e\x64\x65vice_detailsB3Z1go.chromium.org/chromiumos/config/go/test/lab/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.test.lab.api.pasit_host_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1go.chromium.org/chromiumos/config/go/test/lab/api'
  _globals['_PASITHOST']._serialized_start=105
  _globals['_PASITHOST']._serialized_end=1088
  _globals['_PASITHOST_CONNECTION']._serialized_start=264
  _globals['_PASITHOST_CONNECTION']._serialized_end=377
  _globals['_PASITHOST_DEVICE']._serialized_start=380
  _globals['_PASITHOST_DEVICE']._serialized_end=1088
  _globals['_PASITHOST_DEVICE_POWERSUPPLY']._serialized_start=723
  _globals['_PASITHOST_DEVICE_POWERSUPPLY']._serialized_end=785
  _globals['_PASITHOST_DEVICE_SWITCHFIXTUREDETAILS']._serialized_start=787
  _globals['_PASITHOST_DEVICE_SWITCHFIXTUREDETAILS']._serialized_end=862
  _globals['_PASITHOST_DEVICE_TYPE']._serialized_start=865
  _globals['_PASITHOST_DEVICE_TYPE']._serialized_end=1070
# @@protoc_insertion_point(module_scope)
