# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_platform/steps/ctpv2_binary.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.test_platform.config import config_pb2 as test__platform_dot_config_dot_config__pb2
from chromite.api.gen_sdk.test_platform import request_pb2 as test__platform_dot_request__pb2
from chromite.api.gen_sdk.chromiumos.test.api import ctp2_pb2 as chromiumos_dot_test_dot_api_dot_ctp2__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='test_platform/steps/ctpv2_binary.proto',
  package='test_platform.steps',
  syntax='proto3',
  serialized_options=b'Z=go.chromium.org/chromiumos/infra/proto/go/test_platform/steps',
  serialized_pb=b'\n&test_platform/steps/ctpv2_binary.proto\x12\x13test_platform.steps\x1a!test_platform/config/config.proto\x1a\x1btest_platform/request.proto\x1a\x1e\x63hromiumos/test/api/ctp2.proto\"\xbd\x02\n\x15\x43TPv2BinaryBuildInput\x12\'\n\x07request\x18\x01 \x01(\x0b\x32\x16.test_platform.Request\x12J\n\x08requests\x18\x02 \x03(\x0b\x32\x38.test_platform.steps.CTPv2BinaryBuildInput.RequestsEntry\x12,\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x1c.test_platform.config.Config\x12\x38\n\rctpv2_request\x18\x04 \x01(\x0b\x32!.chromiumos.test.api.CTPv2Request\x1aG\n\rRequestsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.test_platform.Request:\x02\x38\x01\"\xaa\x01\n\x16\x43TPv2BinaryBuildOutput\x12\x1e\n\x16\x65rror_summary_markdown\x18\x01 \x01(\t\x12\x32\n\x14\x63ompressed_responses\x18\x02 \x01(\tR\x14\x63ompressed_responses\x12<\n\x19\x63ompressed_json_responses\x18\x03 \x01(\tR\x19\x63ompressed_json_responsesB?Z=go.chromium.org/chromiumos/infra/proto/go/test_platform/stepsb\x06proto3'
  ,
  dependencies=[test__platform_dot_config_dot_config__pb2.DESCRIPTOR,test__platform_dot_request__pb2.DESCRIPTOR,chromiumos_dot_test_dot_api_dot_ctp2__pb2.DESCRIPTOR,])




_CTPV2BINARYBUILDINPUT_REQUESTSENTRY = _descriptor.Descriptor(
  name='RequestsEntry',
  full_name='test_platform.steps.CTPv2BinaryBuildInput.RequestsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='test_platform.steps.CTPv2BinaryBuildInput.RequestsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='test_platform.steps.CTPv2BinaryBuildInput.RequestsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=477,
)

_CTPV2BINARYBUILDINPUT = _descriptor.Descriptor(
  name='CTPv2BinaryBuildInput',
  full_name='test_platform.steps.CTPv2BinaryBuildInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='test_platform.steps.CTPv2BinaryBuildInput.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requests', full_name='test_platform.steps.CTPv2BinaryBuildInput.requests', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='test_platform.steps.CTPv2BinaryBuildInput.config', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ctpv2_request', full_name='test_platform.steps.CTPv2BinaryBuildInput.ctpv2_request', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CTPV2BINARYBUILDINPUT_REQUESTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=477,
)


_CTPV2BINARYBUILDOUTPUT = _descriptor.Descriptor(
  name='CTPv2BinaryBuildOutput',
  full_name='test_platform.steps.CTPv2BinaryBuildOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_summary_markdown', full_name='test_platform.steps.CTPv2BinaryBuildOutput.error_summary_markdown', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compressed_responses', full_name='test_platform.steps.CTPv2BinaryBuildOutput.compressed_responses', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='compressed_responses', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compressed_json_responses', full_name='test_platform.steps.CTPv2BinaryBuildOutput.compressed_json_responses', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='compressed_json_responses', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=650,
)

_CTPV2BINARYBUILDINPUT_REQUESTSENTRY.fields_by_name['value'].message_type = test__platform_dot_request__pb2._REQUEST
_CTPV2BINARYBUILDINPUT_REQUESTSENTRY.containing_type = _CTPV2BINARYBUILDINPUT
_CTPV2BINARYBUILDINPUT.fields_by_name['request'].message_type = test__platform_dot_request__pb2._REQUEST
_CTPV2BINARYBUILDINPUT.fields_by_name['requests'].message_type = _CTPV2BINARYBUILDINPUT_REQUESTSENTRY
_CTPV2BINARYBUILDINPUT.fields_by_name['config'].message_type = test__platform_dot_config_dot_config__pb2._CONFIG
_CTPV2BINARYBUILDINPUT.fields_by_name['ctpv2_request'].message_type = chromiumos_dot_test_dot_api_dot_ctp2__pb2._CTPV2REQUEST
DESCRIPTOR.message_types_by_name['CTPv2BinaryBuildInput'] = _CTPV2BINARYBUILDINPUT
DESCRIPTOR.message_types_by_name['CTPv2BinaryBuildOutput'] = _CTPV2BINARYBUILDOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CTPv2BinaryBuildInput = _reflection.GeneratedProtocolMessageType('CTPv2BinaryBuildInput', (_message.Message,), {

  'RequestsEntry' : _reflection.GeneratedProtocolMessageType('RequestsEntry', (_message.Message,), {
    'DESCRIPTOR' : _CTPV2BINARYBUILDINPUT_REQUESTSENTRY,
    '__module__' : 'test_platform.steps.ctpv2_binary_pb2'
    # @@protoc_insertion_point(class_scope:test_platform.steps.CTPv2BinaryBuildInput.RequestsEntry)
    })
  ,
  'DESCRIPTOR' : _CTPV2BINARYBUILDINPUT,
  '__module__' : 'test_platform.steps.ctpv2_binary_pb2'
  # @@protoc_insertion_point(class_scope:test_platform.steps.CTPv2BinaryBuildInput)
  })
_sym_db.RegisterMessage(CTPv2BinaryBuildInput)
_sym_db.RegisterMessage(CTPv2BinaryBuildInput.RequestsEntry)

CTPv2BinaryBuildOutput = _reflection.GeneratedProtocolMessageType('CTPv2BinaryBuildOutput', (_message.Message,), {
  'DESCRIPTOR' : _CTPV2BINARYBUILDOUTPUT,
  '__module__' : 'test_platform.steps.ctpv2_binary_pb2'
  # @@protoc_insertion_point(class_scope:test_platform.steps.CTPv2BinaryBuildOutput)
  })
_sym_db.RegisterMessage(CTPv2BinaryBuildOutput)


DESCRIPTOR._options = None
_CTPV2BINARYBUILDINPUT_REQUESTSENTRY._options = None
# @@protoc_insertion_point(module_scope)
