# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromite/api/build_api.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromite/api/build_api.proto',
  package='chromite.api',
  syntax='proto2',
  serialized_options=b'Z6go.chromium.org/chromiumos/infra/proto/go/chromite/api',
  serialized_pb=b'\n\x1c\x63hromite/api/build_api.proto\x12\x0c\x63hromite.api\x1a google/protobuf/descriptor.proto\"\xe5\x01\n\x16\x42uildApiServiceOptions\x12\x0e\n\x06module\x18\x01 \x02(\t\x12<\n\x15service_chroot_assert\x18\x02 \x01(\x0e\x32\x1d.chromite.api.ChrootAssertion\x12\x38\n\x12service_visibility\x18\x03 \x01(\x0e\x32\x1c.chromite.api.ListVisibility\x12\x43\n\x1aservice_branched_execution\x18\x04 \x01(\x0e\x32\x1f.chromite.api.BranchedExecution\"\xee\x01\n\x15\x42uildApiMethodOptions\x12\x1b\n\x13implementation_name\x18\x01 \x01(\t\x12;\n\x14method_chroot_assert\x18\x02 \x01(\x0e\x32\x1d.chromite.api.ChrootAssertion\x12\x37\n\x11method_visibility\x18\x03 \x01(\x0e\x32\x1c.chromite.api.ListVisibility\x12\x42\n\x19method_branched_execution\x18\x04 \x01(\x0e\x32\x1f.chromite.api.BranchedExecution*<\n\x0f\x43hrootAssertion\x12\x10\n\x0cNO_ASSERTION\x10\x00\x12\n\n\x06INSIDE\x10\x01\x12\x0b\n\x07OUTSIDE\x10\x02*E\n\x0eListVisibility\x12\x14\n\x10LV_NOT_SPECIFIED\x10\x00\x12\x0e\n\nLV_VISIBLE\x10\x01\x12\r\n\tLV_HIDDEN\x10\x02*U\n\x11\x42ranchedExecution\x12\x19\n\x15\x45XECUTE_NOT_SPECIFIED\x10\x00\x12\x14\n\x10\x45XECUTE_BRANCHED\x10\x01\x12\x0f\n\x0b\x45XECUTE_TOT\x10\x02:`\n\x0fservice_options\x12\x1f.google.protobuf.ServiceOptions\x18\xd8\xad\x03 \x01(\x0b\x32$.chromite.api.BuildApiServiceOptions:]\n\x0emethod_options\x12\x1e.google.protobuf.MethodOptions\x18\xd8\xad\x03 \x01(\x0b\x32#.chromite.api.BuildApiMethodOptionsB8Z6go.chromium.org/chromiumos/infra/proto/go/chromite/api'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])

_CHROOTASSERTION = _descriptor.EnumDescriptor(
  name='ChrootAssertion',
  full_name='chromite.api.ChrootAssertion',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_ASSERTION', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INSIDE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OUTSIDE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=553,
  serialized_end=613,
)
_sym_db.RegisterEnumDescriptor(_CHROOTASSERTION)

ChrootAssertion = enum_type_wrapper.EnumTypeWrapper(_CHROOTASSERTION)
_LISTVISIBILITY = _descriptor.EnumDescriptor(
  name='ListVisibility',
  full_name='chromite.api.ListVisibility',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LV_NOT_SPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LV_VISIBLE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LV_HIDDEN', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=615,
  serialized_end=684,
)
_sym_db.RegisterEnumDescriptor(_LISTVISIBILITY)

ListVisibility = enum_type_wrapper.EnumTypeWrapper(_LISTVISIBILITY)
_BRANCHEDEXECUTION = _descriptor.EnumDescriptor(
  name='BranchedExecution',
  full_name='chromite.api.BranchedExecution',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EXECUTE_NOT_SPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXECUTE_BRANCHED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXECUTE_TOT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=686,
  serialized_end=771,
)
_sym_db.RegisterEnumDescriptor(_BRANCHEDEXECUTION)

BranchedExecution = enum_type_wrapper.EnumTypeWrapper(_BRANCHEDEXECUTION)
NO_ASSERTION = 0
INSIDE = 1
OUTSIDE = 2
LV_NOT_SPECIFIED = 0
LV_VISIBLE = 1
LV_HIDDEN = 2
EXECUTE_NOT_SPECIFIED = 0
EXECUTE_BRANCHED = 1
EXECUTE_TOT = 2

SERVICE_OPTIONS_FIELD_NUMBER = 55000
service_options = _descriptor.FieldDescriptor(
  name='service_options', full_name='chromite.api.service_options', index=0,
  number=55000, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
METHOD_OPTIONS_FIELD_NUMBER = 55000
method_options = _descriptor.FieldDescriptor(
  name='method_options', full_name='chromite.api.method_options', index=1,
  number=55000, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)


_BUILDAPISERVICEOPTIONS = _descriptor.Descriptor(
  name='BuildApiServiceOptions',
  full_name='chromite.api.BuildApiServiceOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='module', full_name='chromite.api.BuildApiServiceOptions.module', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_chroot_assert', full_name='chromite.api.BuildApiServiceOptions.service_chroot_assert', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_visibility', full_name='chromite.api.BuildApiServiceOptions.service_visibility', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_branched_execution', full_name='chromite.api.BuildApiServiceOptions.service_branched_execution', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=310,
)


_BUILDAPIMETHODOPTIONS = _descriptor.Descriptor(
  name='BuildApiMethodOptions',
  full_name='chromite.api.BuildApiMethodOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='implementation_name', full_name='chromite.api.BuildApiMethodOptions.implementation_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method_chroot_assert', full_name='chromite.api.BuildApiMethodOptions.method_chroot_assert', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method_visibility', full_name='chromite.api.BuildApiMethodOptions.method_visibility', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method_branched_execution', full_name='chromite.api.BuildApiMethodOptions.method_branched_execution', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=551,
)

_BUILDAPISERVICEOPTIONS.fields_by_name['service_chroot_assert'].enum_type = _CHROOTASSERTION
_BUILDAPISERVICEOPTIONS.fields_by_name['service_visibility'].enum_type = _LISTVISIBILITY
_BUILDAPISERVICEOPTIONS.fields_by_name['service_branched_execution'].enum_type = _BRANCHEDEXECUTION
_BUILDAPIMETHODOPTIONS.fields_by_name['method_chroot_assert'].enum_type = _CHROOTASSERTION
_BUILDAPIMETHODOPTIONS.fields_by_name['method_visibility'].enum_type = _LISTVISIBILITY
_BUILDAPIMETHODOPTIONS.fields_by_name['method_branched_execution'].enum_type = _BRANCHEDEXECUTION
DESCRIPTOR.message_types_by_name['BuildApiServiceOptions'] = _BUILDAPISERVICEOPTIONS
DESCRIPTOR.message_types_by_name['BuildApiMethodOptions'] = _BUILDAPIMETHODOPTIONS
DESCRIPTOR.enum_types_by_name['ChrootAssertion'] = _CHROOTASSERTION
DESCRIPTOR.enum_types_by_name['ListVisibility'] = _LISTVISIBILITY
DESCRIPTOR.enum_types_by_name['BranchedExecution'] = _BRANCHEDEXECUTION
DESCRIPTOR.extensions_by_name['service_options'] = service_options
DESCRIPTOR.extensions_by_name['method_options'] = method_options
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuildApiServiceOptions = _reflection.GeneratedProtocolMessageType('BuildApiServiceOptions', (_message.Message,), {
  'DESCRIPTOR' : _BUILDAPISERVICEOPTIONS,
  '__module__' : 'chromite.api.build_api_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.BuildApiServiceOptions)
  })
_sym_db.RegisterMessage(BuildApiServiceOptions)

BuildApiMethodOptions = _reflection.GeneratedProtocolMessageType('BuildApiMethodOptions', (_message.Message,), {
  'DESCRIPTOR' : _BUILDAPIMETHODOPTIONS,
  '__module__' : 'chromite.api.build_api_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.BuildApiMethodOptions)
  })
_sym_db.RegisterMessage(BuildApiMethodOptions)

service_options.message_type = _BUILDAPISERVICEOPTIONS
google_dot_protobuf_dot_descriptor__pb2.ServiceOptions.RegisterExtension(service_options)
method_options.message_type = _BUILDAPIMETHODOPTIONS
google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(method_options)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
