# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromite/api/chrome_lkgm.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromite.api import build_api_pb2 as chromite_dot_api_dot_build__api__pb2
from chromite.api.gen_sdk.chromiumos import common_pb2 as chromiumos_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromite/api/chrome_lkgm.proto',
  package='chromite.api',
  syntax='proto3',
  serialized_options=b'Z6go.chromium.org/chromiumos/infra/proto/go/chromite/api',
  serialized_pb=b'\n\x1e\x63hromite/api/chrome_lkgm.proto\x12\x0c\x63hromite.api\x1a\x1c\x63hromite/api/build_api.proto\x1a\x17\x63hromiumos/common.proto\"\x9f\x01\n\x0f\x46indLkgmRequest\x12\x12\n\nchrome_src\x18\x01 \x01(\t\x12\x11\n\tcache_dir\x18\x02 \x01(\t\x12-\n\x0c\x62uild_target\x18\x03 \x01(\x0b\x32\x17.chromiumos.BuildTarget\x12\x19\n\x11\x66\x61llback_versions\x18\x04 \x01(\r\x12\x1b\n\x13use_external_config\x18\x05 \x01(\x08\"c\n\x10\x46indLkgmResponse\x12\x15\n\rchromeos_lkgm\x18\x01 \x01(\t\x12\x13\n\x0b\x63onfig_name\x18\x02 \x01(\t\x12\x14\n\x0c\x66ull_version\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t2q\n\x11\x43hromeLkgmService\x12I\n\x08\x46indLkgm\x12\x1d.chromite.api.FindLkgmRequest\x1a\x1e.chromite.api.FindLkgmResponse\x1a\x11\xc2\xed\x1a\r\n\x0b\x63hrome_lkgmB8Z6go.chromium.org/chromiumos/infra/proto/go/chromite/apib\x06proto3'
  ,
  dependencies=[chromite_dot_api_dot_build__api__pb2.DESCRIPTOR,chromiumos_dot_common__pb2.DESCRIPTOR,])




_FINDLKGMREQUEST = _descriptor.Descriptor(
  name='FindLkgmRequest',
  full_name='chromite.api.FindLkgmRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chrome_src', full_name='chromite.api.FindLkgmRequest.chrome_src', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cache_dir', full_name='chromite.api.FindLkgmRequest.cache_dir', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_target', full_name='chromite.api.FindLkgmRequest.build_target', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fallback_versions', full_name='chromite.api.FindLkgmRequest.fallback_versions', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_external_config', full_name='chromite.api.FindLkgmRequest.use_external_config', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=263,
)


_FINDLKGMRESPONSE = _descriptor.Descriptor(
  name='FindLkgmResponse',
  full_name='chromite.api.FindLkgmResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chromeos_lkgm', full_name='chromite.api.FindLkgmResponse.chromeos_lkgm', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config_name', full_name='chromite.api.FindLkgmResponse.config_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='full_version', full_name='chromite.api.FindLkgmResponse.full_version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='chromite.api.FindLkgmResponse.error', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=364,
)

_FINDLKGMREQUEST.fields_by_name['build_target'].message_type = chromiumos_dot_common__pb2._BUILDTARGET
DESCRIPTOR.message_types_by_name['FindLkgmRequest'] = _FINDLKGMREQUEST
DESCRIPTOR.message_types_by_name['FindLkgmResponse'] = _FINDLKGMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FindLkgmRequest = _reflection.GeneratedProtocolMessageType('FindLkgmRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINDLKGMREQUEST,
  '__module__' : 'chromite.api.chrome_lkgm_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.FindLkgmRequest)
  })
_sym_db.RegisterMessage(FindLkgmRequest)

FindLkgmResponse = _reflection.GeneratedProtocolMessageType('FindLkgmResponse', (_message.Message,), {
  'DESCRIPTOR' : _FINDLKGMRESPONSE,
  '__module__' : 'chromite.api.chrome_lkgm_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.FindLkgmResponse)
  })
_sym_db.RegisterMessage(FindLkgmResponse)


DESCRIPTOR._options = None

_CHROMELKGMSERVICE = _descriptor.ServiceDescriptor(
  name='ChromeLkgmService',
  full_name='chromite.api.ChromeLkgmService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=b'\302\355\032\r\n\013chrome_lkgm',
  serialized_start=366,
  serialized_end=479,
  methods=[
  _descriptor.MethodDescriptor(
    name='FindLkgm',
    full_name='chromite.api.ChromeLkgmService.FindLkgm',
    index=0,
    containing_service=None,
    input_type=_FINDLKGMREQUEST,
    output_type=_FINDLKGMRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHROMELKGMSERVICE)

DESCRIPTOR.services_by_name['ChromeLkgmService'] = _CHROMELKGMSERVICE

# @@protoc_insertion_point(module_scope)
