# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromite/api/dlc.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromite.api import build_api_pb2 as chromite_dot_api_dot_build__api__pb2
from chromite.api.gen_sdk.chromite.api import sysroot_pb2 as chromite_dot_api_dot_sysroot__pb2
from chromite.api.gen_sdk.chromiumos import common_pb2 as chromiumos_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromite/api/dlc.proto',
  package='chromite.api',
  syntax='proto3',
  serialized_options=b'Z6go.chromium.org/chromiumos/infra/proto/go/chromite/api',
  serialized_pb=b'\n\x16\x63hromite/api/dlc.proto\x12\x0c\x63hromite.api\x1a\x1c\x63hromite/api/build_api.proto\x1a\x1a\x63hromite/api/sysroot.proto\x1a\x17\x63hromiumos/common.proto\"m\n\x1fGenerateDlcArtifactsListRequest\x12\"\n\x06\x63hroot\x18\x01 \x01(\x0b\x32\x12.chromiumos.Chroot\x12&\n\x07sysroot\x18\x02 \x01(\x0b\x32\x15.chromite.api.Sysroot\"\xcd\x01\n GenerateDlcArtifactsListResponse\x12Q\n\rdlc_artifacts\x18\x01 \x03(\x0b\x32:.chromite.api.GenerateDlcArtifactsListResponse.DlcArtifact\x1aV\n\x0b\x44lcArtifact\x12\x12\n\nimage_hash\x18\x01 \x01(\t\x12\x12\n\nimage_name\x18\x02 \x01(\t\x12\x13\n\x0bgs_uri_path\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t2\x94\x01\n\nDlcService\x12y\n\x18GenerateDlcArtifactsList\x12-.chromite.api.GenerateDlcArtifactsListRequest\x1a..chromite.api.GenerateDlcArtifactsListResponse\x1a\x0b\xc2\xed\x1a\x07\n\x03\x64lc\x10\x01\x42\x38Z6go.chromium.org/chromiumos/infra/proto/go/chromite/apib\x06proto3'
  ,
  dependencies=[chromite_dot_api_dot_build__api__pb2.DESCRIPTOR,chromite_dot_api_dot_sysroot__pb2.DESCRIPTOR,chromiumos_dot_common__pb2.DESCRIPTOR,])




_GENERATEDLCARTIFACTSLISTREQUEST = _descriptor.Descriptor(
  name='GenerateDlcArtifactsListRequest',
  full_name='chromite.api.GenerateDlcArtifactsListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chroot', full_name='chromite.api.GenerateDlcArtifactsListRequest.chroot', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sysroot', full_name='chromite.api.GenerateDlcArtifactsListRequest.sysroot', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=232,
)


_GENERATEDLCARTIFACTSLISTRESPONSE_DLCARTIFACT = _descriptor.Descriptor(
  name='DlcArtifact',
  full_name='chromite.api.GenerateDlcArtifactsListResponse.DlcArtifact',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_hash', full_name='chromite.api.GenerateDlcArtifactsListResponse.DlcArtifact.image_hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_name', full_name='chromite.api.GenerateDlcArtifactsListResponse.DlcArtifact.image_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gs_uri_path', full_name='chromite.api.GenerateDlcArtifactsListResponse.DlcArtifact.gs_uri_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='chromite.api.GenerateDlcArtifactsListResponse.DlcArtifact.id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=440,
)

_GENERATEDLCARTIFACTSLISTRESPONSE = _descriptor.Descriptor(
  name='GenerateDlcArtifactsListResponse',
  full_name='chromite.api.GenerateDlcArtifactsListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dlc_artifacts', full_name='chromite.api.GenerateDlcArtifactsListResponse.dlc_artifacts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GENERATEDLCARTIFACTSLISTRESPONSE_DLCARTIFACT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=440,
)

_GENERATEDLCARTIFACTSLISTREQUEST.fields_by_name['chroot'].message_type = chromiumos_dot_common__pb2._CHROOT
_GENERATEDLCARTIFACTSLISTREQUEST.fields_by_name['sysroot'].message_type = chromite_dot_api_dot_sysroot__pb2._SYSROOT
_GENERATEDLCARTIFACTSLISTRESPONSE_DLCARTIFACT.containing_type = _GENERATEDLCARTIFACTSLISTRESPONSE
_GENERATEDLCARTIFACTSLISTRESPONSE.fields_by_name['dlc_artifacts'].message_type = _GENERATEDLCARTIFACTSLISTRESPONSE_DLCARTIFACT
DESCRIPTOR.message_types_by_name['GenerateDlcArtifactsListRequest'] = _GENERATEDLCARTIFACTSLISTREQUEST
DESCRIPTOR.message_types_by_name['GenerateDlcArtifactsListResponse'] = _GENERATEDLCARTIFACTSLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenerateDlcArtifactsListRequest = _reflection.GeneratedProtocolMessageType('GenerateDlcArtifactsListRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERATEDLCARTIFACTSLISTREQUEST,
  '__module__' : 'chromite.api.dlc_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.GenerateDlcArtifactsListRequest)
  })
_sym_db.RegisterMessage(GenerateDlcArtifactsListRequest)

GenerateDlcArtifactsListResponse = _reflection.GeneratedProtocolMessageType('GenerateDlcArtifactsListResponse', (_message.Message,), {

  'DlcArtifact' : _reflection.GeneratedProtocolMessageType('DlcArtifact', (_message.Message,), {
    'DESCRIPTOR' : _GENERATEDLCARTIFACTSLISTRESPONSE_DLCARTIFACT,
    '__module__' : 'chromite.api.dlc_pb2'
    # @@protoc_insertion_point(class_scope:chromite.api.GenerateDlcArtifactsListResponse.DlcArtifact)
    })
  ,
  'DESCRIPTOR' : _GENERATEDLCARTIFACTSLISTRESPONSE,
  '__module__' : 'chromite.api.dlc_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.GenerateDlcArtifactsListResponse)
  })
_sym_db.RegisterMessage(GenerateDlcArtifactsListResponse)
_sym_db.RegisterMessage(GenerateDlcArtifactsListResponse.DlcArtifact)


DESCRIPTOR._options = None

_DLCSERVICE = _descriptor.ServiceDescriptor(
  name='DlcService',
  full_name='chromite.api.DlcService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=b'\302\355\032\007\n\003dlc\020\001',
  serialized_start=443,
  serialized_end=591,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenerateDlcArtifactsList',
    full_name='chromite.api.DlcService.GenerateDlcArtifactsList',
    index=0,
    containing_service=None,
    input_type=_GENERATEDLCARTIFACTSLISTREQUEST,
    output_type=_GENERATEDLCARTIFACTSLISTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DLCSERVICE)

DESCRIPTOR.services_by_name['DlcService'] = _DLCSERVICE

# @@protoc_insertion_point(module_scope)
