# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromite/api/ide.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromite.api import build_api_pb2 as chromite_dot_api_dot_build__api__pb2
from chromite.api.gen_sdk.chromiumos import common_pb2 as chromiumos_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63hromite/api/ide.proto\x12\x0c\x63hromite.api\x1a\x1c\x63hromite/api/build_api.proto\x1a\x17\x63hromiumos/common.proto\"\xea\x02\n\"GenerateMergedCompilationDBRequest\x12\"\n\x06\x63hroot\x18\x01 \x01(\x0b\x32\x12.chromiumos.Chroot\x12-\n\x0c\x62uild_target\x18\x02 \x01(\x0b\x32\x17.chromiumos.BuildTarget\x12#\n\tbuild_dir\x18\x03 \x01(\x0b\x32\x10.chromiumos.Path\x12*\n\x10\x63ompile_commands\x18\x04 \x01(\x0b\x32\x10.chromiumos.Path\x12)\n\x08packages\x18\x05 \x03(\x0b\x32\x17.chromiumos.PackageInfo\x12\x45\n\x05\x66lags\x18\x06 \x01(\x0b\x32\x36.chromite.api.GenerateMergedCompilationDBRequest.Flags\x1a.\n\x05\x46lags\x12\x11\n\tfail_fast\x18\x01 \x01(\x08\x12\x12\n\nwith_tests\x18\x02 \x01(\x08\"%\n#GenerateMergedCompilationDBResponse2\xa4\x01\n\nIdeService\x12\x8a\x01\n\x1bGenerateMergedCompilationDB\x12\x30.chromite.api.GenerateMergedCompilationDBRequest\x1a\x31.chromite.api.GenerateMergedCompilationDBResponse\"\x06\xc2\xed\x1a\x02\x10\x02\x1a\t\xc2\xed\x1a\x05\n\x03ideB8Z6go.chromium.org/chromiumos/infra/proto/go/chromite/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromite.api.ide_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z6go.chromium.org/chromiumos/infra/proto/go/chromite/api'
  _IDESERVICE._options = None
  _IDESERVICE._serialized_options = b'\302\355\032\005\n\003ide'
  _IDESERVICE.methods_by_name['GenerateMergedCompilationDB']._options = None
  _IDESERVICE.methods_by_name['GenerateMergedCompilationDB']._serialized_options = b'\302\355\032\002\020\002'
  _globals['_GENERATEMERGEDCOMPILATIONDBREQUEST']._serialized_start=96
  _globals['_GENERATEMERGEDCOMPILATIONDBREQUEST']._serialized_end=458
  _globals['_GENERATEMERGEDCOMPILATIONDBREQUEST_FLAGS']._serialized_start=412
  _globals['_GENERATEMERGEDCOMPILATIONDBREQUEST_FLAGS']._serialized_end=458
  _globals['_GENERATEMERGEDCOMPILATIONDBRESPONSE']._serialized_start=460
  _globals['_GENERATEMERGEDCOMPILATIONDBRESPONSE']._serialized_end=497
  _globals['_IDESERVICE']._serialized_start=500
  _globals['_IDESERVICE']._serialized_end=664
# @@protoc_insertion_point(module_scope)
