# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromite/api/sdk_subtools.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromite.api import build_api_pb2 as chromite_dot_api_dot_build__api__pb2
from chromite.api.gen_sdk.chromite.api import sysroot_pb2 as chromite_dot_api_dot_sysroot__pb2
from chromite.api.gen_sdk.chromiumos import common_pb2 as chromiumos_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromite/api/sdk_subtools.proto',
  package='chromite.api',
  syntax='proto3',
  serialized_options=b'Z6go.chromium.org/chromiumos/infra/proto/go/chromite/api',
  serialized_pb=b'\n\x1f\x63hromite/api/sdk_subtools.proto\x12\x0c\x63hromite.api\x1a\x1c\x63hromite/api/build_api.proto\x1a\x1a\x63hromite/api/sysroot.proto\x1a\x17\x63hromiumos/common.proto\"=\n\x17\x42uildSdkSubtoolsRequest\x12\"\n\x06\x63hroot\x18\x01 \x01(\x0b\x32\x12.chromiumos.Chroot\"X\n\x18\x42uildSdkSubtoolsResponse\x12<\n\x13\x66\x61iled_package_data\x18\x01 \x03(\x0b\x32\x1f.chromite.api.FailedPackageData2\x92\x01\n\x17\x42uildSdkSubtoolsService\x12\x61\n\x10\x42uildSdkSubtools\x12%.chromite.api.BuildSdkSubtoolsRequest\x1a&.chromite.api.BuildSdkSubtoolsResponse\x1a\x14\xc2\xed\x1a\x10\n\x0csdk_subtools\x10\x01\x42\x38Z6go.chromium.org/chromiumos/infra/proto/go/chromite/apib\x06proto3'
  ,
  dependencies=[chromite_dot_api_dot_build__api__pb2.DESCRIPTOR,chromite_dot_api_dot_sysroot__pb2.DESCRIPTOR,chromiumos_dot_common__pb2.DESCRIPTOR,])




_BUILDSDKSUBTOOLSREQUEST = _descriptor.Descriptor(
  name='BuildSdkSubtoolsRequest',
  full_name='chromite.api.BuildSdkSubtoolsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chroot', full_name='chromite.api.BuildSdkSubtoolsRequest.chroot', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=193,
)


_BUILDSDKSUBTOOLSRESPONSE = _descriptor.Descriptor(
  name='BuildSdkSubtoolsResponse',
  full_name='chromite.api.BuildSdkSubtoolsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='failed_package_data', full_name='chromite.api.BuildSdkSubtoolsResponse.failed_package_data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=283,
)

_BUILDSDKSUBTOOLSREQUEST.fields_by_name['chroot'].message_type = chromiumos_dot_common__pb2._CHROOT
_BUILDSDKSUBTOOLSRESPONSE.fields_by_name['failed_package_data'].message_type = chromite_dot_api_dot_sysroot__pb2._FAILEDPACKAGEDATA
DESCRIPTOR.message_types_by_name['BuildSdkSubtoolsRequest'] = _BUILDSDKSUBTOOLSREQUEST
DESCRIPTOR.message_types_by_name['BuildSdkSubtoolsResponse'] = _BUILDSDKSUBTOOLSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuildSdkSubtoolsRequest = _reflection.GeneratedProtocolMessageType('BuildSdkSubtoolsRequest', (_message.Message,), {
  'DESCRIPTOR' : _BUILDSDKSUBTOOLSREQUEST,
  '__module__' : 'chromite.api.sdk_subtools_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.BuildSdkSubtoolsRequest)
  })
_sym_db.RegisterMessage(BuildSdkSubtoolsRequest)

BuildSdkSubtoolsResponse = _reflection.GeneratedProtocolMessageType('BuildSdkSubtoolsResponse', (_message.Message,), {
  'DESCRIPTOR' : _BUILDSDKSUBTOOLSRESPONSE,
  '__module__' : 'chromite.api.sdk_subtools_pb2'
  # @@protoc_insertion_point(class_scope:chromite.api.BuildSdkSubtoolsResponse)
  })
_sym_db.RegisterMessage(BuildSdkSubtoolsResponse)


DESCRIPTOR._options = None

_BUILDSDKSUBTOOLSSERVICE = _descriptor.ServiceDescriptor(
  name='BuildSdkSubtoolsService',
  full_name='chromite.api.BuildSdkSubtoolsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=b'\302\355\032\020\n\014sdk_subtools\020\001',
  serialized_start=286,
  serialized_end=432,
  methods=[
  _descriptor.MethodDescriptor(
    name='BuildSdkSubtools',
    full_name='chromite.api.BuildSdkSubtoolsService.BuildSdkSubtools',
    index=0,
    containing_service=None,
    input_type=_BUILDSDKSUBTOOLSREQUEST,
    output_type=_BUILDSDKSUBTOOLSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BUILDSDKSUBTOOLSSERVICE)

DESCRIPTOR.services_by_name['BuildSdkSubtoolsService'] = _BUILDSDKSUBTOOLSSERVICE

# @@protoc_insertion_point(module_scope)
