# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromite/api/sdk_subtools.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromite.api import build_api_pb2 as chromite_dot_api_dot_build__api__pb2
from chromite.api.gen_sdk.chromite.api import sysroot_pb2 as chromite_dot_api_dot_sysroot__pb2
from chromite.api.gen_sdk.chromiumos import common_pb2 as chromiumos_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63hromite/api/sdk_subtools.proto\x12\x0c\x63hromite.api\x1a\x1c\x63hromite/api/build_api.proto\x1a\x1a\x63hromite/api/sysroot.proto\x1a\x17\x63hromiumos/common.proto\"\x92\x02\n\x17\x42uildSdkSubtoolsRequest\x12\"\n\x06\x63hroot\x18\x01 \x01(\x0b\x32\x12.chromiumos.Chroot\x12)\n\x08packages\x18\x02 \x03(\x0b\x32\x17.chromiumos.PackageInfo\x12+\n\x0bresult_path\x18\x03 \x01(\x0b\x32\x16.chromiumos.ResultPath\x12H\n\rupload_filter\x18\x04 \x03(\x0b\x32\x31.chromite.api.BuildSdkSubtoolsRequest.SubtoolName\x12\x14\n\x0cprivate_only\x18\x05 \x01(\x08\x1a\x1b\n\x0bSubtoolName\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x80\x01\n\x18\x42uildSdkSubtoolsResponse\x12<\n\x13\x66\x61iled_package_data\x18\x01 \x03(\x0b\x32\x1f.chromite.api.FailedPackageData\x12&\n\x0c\x62undle_paths\x18\x02 \x03(\x0b\x32\x10.chromiumos.Path\"Z\n\x18UploadSdkSubtoolsRequest\x12\x16\n\x0euse_production\x18\x01 \x01(\x08\x12&\n\x0c\x62undle_paths\x18\x02 \x03(\x0b\x32\x10.chromiumos.Path\"H\n\x19UploadSdkSubtoolsResponse\x12\x11\n\tstep_text\x18\x01 \x01(\t\x12\x18\n\x10summary_markdown\x18\x02 \x01(\t2\xfb\x01\n\x12SdkSubtoolsService\x12\x61\n\x10\x42uildSdkSubtools\x12%.chromite.api.BuildSdkSubtoolsRequest\x1a&.chromite.api.BuildSdkSubtoolsResponse\x12l\n\x11UploadSdkSubtools\x12&.chromite.api.UploadSdkSubtoolsRequest\x1a\'.chromite.api.UploadSdkSubtoolsResponse\"\x06\xc2\xed\x1a\x02\x10\x02\x1a\x14\xc2\xed\x1a\x10\n\x0csdk_subtools\x10\x01\x42\x38Z6go.chromium.org/chromiumos/infra/proto/go/chromite/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromite.api.sdk_subtools_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z6go.chromium.org/chromiumos/infra/proto/go/chromite/api'
  _SDKSUBTOOLSSERVICE._options = None
  _SDKSUBTOOLSSERVICE._serialized_options = b'\302\355\032\020\n\014sdk_subtools\020\001'
  _SDKSUBTOOLSSERVICE.methods_by_name['UploadSdkSubtools']._options = None
  _SDKSUBTOOLSSERVICE.methods_by_name['UploadSdkSubtools']._serialized_options = b'\302\355\032\002\020\002'
  _globals['_BUILDSDKSUBTOOLSREQUEST']._serialized_start=133
  _globals['_BUILDSDKSUBTOOLSREQUEST']._serialized_end=407
  _globals['_BUILDSDKSUBTOOLSREQUEST_SUBTOOLNAME']._serialized_start=380
  _globals['_BUILDSDKSUBTOOLSREQUEST_SUBTOOLNAME']._serialized_end=407
  _globals['_BUILDSDKSUBTOOLSRESPONSE']._serialized_start=410
  _globals['_BUILDSDKSUBTOOLSRESPONSE']._serialized_end=538
  _globals['_UPLOADSDKSUBTOOLSREQUEST']._serialized_start=540
  _globals['_UPLOADSDKSUBTOOLSREQUEST']._serialized_end=630
  _globals['_UPLOADSDKSUBTOOLSRESPONSE']._serialized_start=632
  _globals['_UPLOADSDKSUBTOOLSRESPONSE']._serialized_end=704
  _globals['_SDKSUBTOOLSSERVICE']._serialized_start=707
  _globals['_SDKSUBTOOLSSERVICE']._serialized_end=958
# @@protoc_insertion_point(module_scope)
