# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromite/api/third_party_inventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromite.api import build_api_pb2 as chromite_dot_api_dot_build__api__pb2
from chromite.api.gen_sdk.chromite.api import sysroot_pb2 as chromite_dot_api_dot_sysroot__pb2
from chromite.api.gen_sdk.chromiumos import common_pb2 as chromiumos_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(chromite/api/third_party_inventory.proto\x12\x0c\x63hromite.api\x1a\x1c\x63hromite/api/build_api.proto\x1a\x1a\x63hromite/api/sysroot.proto\x1a\x17\x63hromiumos/common.proto\"k\n\x1d\x43ollectPackageMetadataRequest\x12\"\n\x06\x63hroot\x18\x01 \x01(\x0b\x32\x12.chromiumos.Chroot\x12&\n\x07sysroot\x18\x02 \x01(\x0b\x32\x15.chromite.api.Sysroot\"M\n\x1e\x43ollectPackageMetadataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1a\n\x12metadata_protojson\x18\x02 \x03(\t2\xb0\x01\n\x1aThirdPartyInventoryService\x12s\n\x16\x43ollectPackageMetadata\x12+.chromite.api.CollectPackageMetadataRequest\x1a,.chromite.api.CollectPackageMetadataResponse\x1a\x1d\xc2\xed\x1a\x19\n\x15third_party_inventory\x10\x01\x42\x38Z6go.chromium.org/chromiumos/infra/proto/go/chromite/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromite.api.third_party_inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z6go.chromium.org/chromiumos/infra/proto/go/chromite/api'
  _THIRDPARTYINVENTORYSERVICE._options = None
  _THIRDPARTYINVENTORYSERVICE._serialized_options = b'\302\355\032\031\n\025third_party_inventory\020\001'
  _globals['_COLLECTPACKAGEMETADATAREQUEST']._serialized_start=141
  _globals['_COLLECTPACKAGEMETADATAREQUEST']._serialized_end=248
  _globals['_COLLECTPACKAGEMETADATARESPONSE']._serialized_start=250
  _globals['_COLLECTPACKAGEMETADATARESPONSE']._serialized_end=327
  _globals['_THIRDPARTYINVENTORYSERVICE']._serialized_start=330
  _globals['_THIRDPARTYINVENTORYSERVICE']._serialized_end=506
# @@protoc_insertion_point(module_scope)
