# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/cros_test_platform.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromiumos.test.api import test_suite_pb2 as chromiumos_dot_test_dot_api_dot_test__suite__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,chromiumos/test/api/cros_test_platform.proto\x12\x13\x63hromiumos.test.api\x1a$chromiumos/test/api/test_suite.proto\"\xd7\x01\n\x0b\x43TPRequest2\x12\x33\n\x0btest_suites\x18\x01 \x03(\x0b\x32\x1e.chromiumos.test.api.TestSuite\x12\x33\n\x0ekarbon_filters\x18\x02 \x03(\x0b\x32\x1b.chromiumos.test.api.Filter\x12\x33\n\x0ekoffee_filters\x18\x03 \x03(\x0b\x32\x1b.chromiumos.test.api.Filter\x12\r\n\x05\x62uild\x18\x04 \x01(\t\x12\x0f\n\x05\x62oard\x18\x05 \x01(\tH\x00\x42\t\n\x07variant\"C\n\x0c\x43TPResponse2\x12\x33\n\x0btest_suites\x18\x01 \x03(\x0b\x32\x1e.chromiumos.test.api.TestSuite\"\x81\x01\n\x06\x46ilter\x12\x35\n\tcontainer\x18\x01 \x01(\x0b\x32\".chromiumos.test.api.ContainerInfo\x12@\n\x14\x64\x65pendent_containers\x18\x02 \x03(\x0b\x32\".chromiumos.test.api.ContainerInfo\"=\n\rContainerInfo\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x16\n\x0e\x63ontainer_path\x18\x02 \x01(\t2r\n\x18\x43rosTestPlatform2Service\x12V\n\x0fRequestResolver\x12 .chromiumos.test.api.CTPRequest2\x1a!.chromiumos.test.api.CTPResponse2B/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.test.api.cros_test_platform_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/api'
  _CTPREQUEST2._serialized_start=108
  _CTPREQUEST2._serialized_end=323
  _CTPRESPONSE2._serialized_start=325
  _CTPRESPONSE2._serialized_end=392
  _FILTER._serialized_start=395
  _FILTER._serialized_end=524
  _CONTAINERINFO._serialized_start=526
  _CONTAINERINFO._serialized_end=587
  _CROSTESTPLATFORM2SERVICE._serialized_start=589
  _CROSTESTPLATFORM2SERVICE._serialized_end=703
# @@protoc_insertion_point(module_scope)
