# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/ctp2_filters.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&chromiumos/test/api/ctp2_filters.proto\x12\x13\x63hromiumos.test.api\"\x8a\x02\n\x1aGenericFilterStreamRequest\x12S\n\x1ainternal_testplan_fragment\x18\x01 \x01(\x0b\x32-.chromiumos.test.api.InternalTestplanFragmentH\x00\x12\x43\n\rauth_fragment\x18\x02 \x01(\x0b\x32*.chromiumos.test.api.AuthorizationFragmentH\x00\x12G\n\x14\x66ilter_args_fragment\x18\x03 \x01(\x0b\x32\'.chromiumos.test.api.FilterArgsFragmentH\x00\x42\t\n\x07message\"\xfc\x01\n\x1bGenericFilterStreamResponse\x12S\n\x1ainternal_testplan_fragment\x18\x01 \x01(\x0b\x32-.chromiumos.test.api.InternalTestplanFragmentH\x00\x12\x38\n\x0clog_fragment\x18\x02 \x01(\x0b\x32 .chromiumos.test.api.LogFragmentH\x00\x12\x43\n\rauth_fragment\x18\x03 \x01(\x0b\x32*.chromiumos.test.api.AuthorizationFragmentH\x00\x42\t\n\x07message\"e\n\x10\x46ragmentMetadata\x12\x12\n\ntotal_size\x18\x01 \x01(\x03\x12\x17\n\x0ftotal_fragments\x18\x02 \x01(\x03\x12\r\n\x05index\x18\x03 \x01(\x03\x12\x15\n\rfragment_size\x18\x04 \x01(\x03\"e\n\x18InternalTestplanFragment\x12\x10\n\x08\x66ragment\x18\x01 \x01(\x0c\x12\x37\n\x08metadata\x18\x02 \x01(\x0b\x32%.chromiumos.test.api.FragmentMetadata\"X\n\x0bLogFragment\x12\x10\n\x08\x66ragment\x18\x01 \x01(\x0c\x12\x37\n\x08metadata\x18\x02 \x01(\x0b\x32%.chromiumos.test.api.FragmentMetadata\"@\n\x14\x41uthorizationRequest\x12\x18\n\x10\x63redential_paths\x18\x01 \x03(\t\x12\x0e\n\x06scopes\x18\x02 \x03(\t\"&\n\x15\x41uthorizationResponse\x12\r\n\x05token\x18\x01 \x01(\t\"b\n\x15\x41uthorizationFragment\x12\x10\n\x08\x66ragment\x18\x01 \x01(\x0c\x12\x37\n\x08metadata\x18\x02 \x01(\x0b\x32%.chromiumos.test.api.FragmentMetadata\"\x1a\n\nFilterArgs\x12\x0c\n\x04\x61rgs\x18\x01 \x03(\t\"_\n\x12\x46ilterArgsFragment\x12\x10\n\x08\x66ragment\x18\x01 \x01(\x0c\x12\x37\n\x08metadata\x18\x02 \x01(\x0b\x32%.chromiumos.test.api.FragmentMetadataB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.test.api.ctp2_filters_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/api'
  _globals['_GENERICFILTERSTREAMREQUEST']._serialized_start=64
  _globals['_GENERICFILTERSTREAMREQUEST']._serialized_end=330
  _globals['_GENERICFILTERSTREAMRESPONSE']._serialized_start=333
  _globals['_GENERICFILTERSTREAMRESPONSE']._serialized_end=585
  _globals['_FRAGMENTMETADATA']._serialized_start=587
  _globals['_FRAGMENTMETADATA']._serialized_end=688
  _globals['_INTERNALTESTPLANFRAGMENT']._serialized_start=690
  _globals['_INTERNALTESTPLANFRAGMENT']._serialized_end=791
  _globals['_LOGFRAGMENT']._serialized_start=793
  _globals['_LOGFRAGMENT']._serialized_end=881
  _globals['_AUTHORIZATIONREQUEST']._serialized_start=883
  _globals['_AUTHORIZATIONREQUEST']._serialized_end=947
  _globals['_AUTHORIZATIONRESPONSE']._serialized_start=949
  _globals['_AUTHORIZATIONRESPONSE']._serialized_end=987
  _globals['_AUTHORIZATIONFRAGMENT']._serialized_start=989
  _globals['_AUTHORIZATIONFRAGMENT']._serialized_end=1087
  _globals['_FILTERARGS']._serialized_start=1089
  _globals['_FILTERARGS']._serialized_end=1115
  _globals['_FILTERARGSFRAGMENT']._serialized_start=1117
  _globals['_FILTERARGSFRAGMENT']._serialized_end=1212
# @@protoc_insertion_point(module_scope)
