# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/logging_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)chromiumos/test/api/logging_service.proto\x12\x13\x63hromiumos.test.api\x1a\x19google/protobuf/any.proto\"=\n\x13StartLoggingRequest\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"\xd7\x01\n\x14StartLoggingResponse\x12@\n\x06status\x18\x01 \x01(\x0e\x32\x30.chromiumos.test.api.StartLoggingResponse.Status\x12&\n\x08metadata\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x0f\n\x07message\x18\x03 \x01(\t\"D\n\x06Status\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n\x0eSTATUS_SUCCESS\x10\x01\x12\x12\n\x0eSTATUS_FAILURE\x10\x02\"<\n\x12StopLoggingRequest\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"\xd5\x01\n\x13StopLoggingResponse\x12?\n\x06status\x18\x01 \x01(\x0e\x32/.chromiumos.test.api.StopLoggingResponse.Status\x12&\n\x08metadata\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x0f\n\x07message\x18\x03 \x01(\t\"D\n\x06Status\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n\x0eSTATUS_SUCCESS\x10\x01\x12\x12\n\x0eSTATUS_FAILURE\x10\x02\x32\xc9\x01\n\x0eLoggingService\x12\\\n\x05Start\x12(.chromiumos.test.api.StartLoggingRequest\x1a).chromiumos.test.api.StartLoggingResponse\x12Y\n\x04Stop\x12\'.chromiumos.test.api.StopLoggingRequest\x1a(.chromiumos.test.api.StopLoggingResponseB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.test.api.logging_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/api'
  _globals['_STARTLOGGINGREQUEST']._serialized_start=93
  _globals['_STARTLOGGINGREQUEST']._serialized_end=154
  _globals['_STARTLOGGINGRESPONSE']._serialized_start=157
  _globals['_STARTLOGGINGRESPONSE']._serialized_end=372
  _globals['_STARTLOGGINGRESPONSE_STATUS']._serialized_start=304
  _globals['_STARTLOGGINGRESPONSE_STATUS']._serialized_end=372
  _globals['_STOPLOGGINGREQUEST']._serialized_start=374
  _globals['_STOPLOGGINGREQUEST']._serialized_end=434
  _globals['_STOPLOGGINGRESPONSE']._serialized_start=437
  _globals['_STOPLOGGINGRESPONSE']._serialized_end=650
  _globals['_STOPLOGGINGRESPONSE_STATUS']._serialized_start=304
  _globals['_STOPLOGGINGRESPONSE_STATUS']._serialized_end=372
  _globals['_LOGGINGSERVICE']._serialized_start=653
  _globals['_LOGGINGSERVICE']._serialized_end=854
# @@protoc_insertion_point(module_scope)
