# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/api/test_harness.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&chromiumos/test/api/test_harness.proto\x12\x13\x63hromiumos.test.api\"\xd8\x04\n\x0bTestHarness\x12\x39\n\x06manual\x18\x01 \x01(\x0b\x32\'.chromiumos.test.api.TestHarness.ManualH\x00\x12\x37\n\x05tauto\x18\x02 \x01(\x0b\x32&.chromiumos.test.api.TestHarness.TautoH\x00\x12\x35\n\x04tast\x18\x03 \x01(\x0b\x32%.chromiumos.test.api.TestHarness.TastH\x00\x12\x37\n\x05gtest\x18\x04 \x01(\x0b\x32&.chromiumos.test.api.TestHarness.GtestH\x00\x12\x37\n\x05mobly\x18\x05 \x01(\x0b\x32&.chromiumos.test.api.TestHarness.MoblyH\x00\x12;\n\x07\x63rosier\x18\x06 \x01(\x0b\x32(.chromiumos.test.api.TestHarness.CrosierH\x00\x12=\n\x08tradefed\x18\x07 \x01(\x0b\x32).chromiumos.test.api.TestHarness.TradefedH\x00\x12\x33\n\x03\x64tc\x18\x08 \x01(\x0b\x32$.chromiumos.test.api.TestHarness.DTCH\x00\x1a\x08\n\x06Manual\x1a\x06\n\x04Tast\x1a\x07\n\x05Tauto\x1a$\n\x05Gtest\x12\x1b\n\x13target_bin_location\x18\x01 \x01(\t\x1a\x07\n\x05Mobly\x1a\t\n\x07\x43rosier\x1a\n\n\x08Tradefed\x1a\x05\n\x03\x44TCB\x13\n\x11test_harness_typeB/Z-go.chromium.org/chromiumos/config/go/test/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.test.api.test_harness_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-go.chromium.org/chromiumos/config/go/test/api'
  _globals['_TESTHARNESS']._serialized_start=64
  _globals['_TESTHARNESS']._serialized_end=664
  _globals['_TESTHARNESS_MANUAL']._serialized_start=541
  _globals['_TESTHARNESS_MANUAL']._serialized_end=549
  _globals['_TESTHARNESS_TAST']._serialized_start=551
  _globals['_TESTHARNESS_TAST']._serialized_end=557
  _globals['_TESTHARNESS_TAUTO']._serialized_start=559
  _globals['_TESTHARNESS_TAUTO']._serialized_end=566
  _globals['_TESTHARNESS_GTEST']._serialized_start=568
  _globals['_TESTHARNESS_GTEST']._serialized_end=604
  _globals['_TESTHARNESS_MOBLY']._serialized_start=606
  _globals['_TESTHARNESS_MOBLY']._serialized_end=613
  _globals['_TESTHARNESS_CROSIER']._serialized_start=615
  _globals['_TESTHARNESS_CROSIER']._serialized_end=624
  _globals['_TESTHARNESS_TRADEFED']._serialized_start=626
  _globals['_TESTHARNESS_TRADEFED']._serialized_end=636
  _globals['_TESTHARNESS_DTC']._serialized_start=638
  _globals['_TESTHARNESS_DTC']._serialized_end=643
# @@protoc_insertion_point(module_scope)
