# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/test/scheduling/device_event.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromiumos.test.scheduling import swarming_dimensions_pb2 as chromiumos_dot_test_dot_scheduling_dot_swarming__dimensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-chromiumos/test/scheduling/device_event.proto\x12\x1a\x63hromiumos.test.scheduling\x1a\x34\x63hromiumos/test/scheduling/swarming_dimensions.proto\"\xa9\x01\n\x0b\x44\x65viceEvent\x12\x12\n\nevent_time\x18\x01 \x01(\x03\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x12\n\x06pod_id\x18\x03 \x01(\rB\x02\x18\x01\x12I\n\x11\x64\x65vice_dimensions\x18\x05 \x01(\x0b\x32..chromiumos.test.scheduling.SwarmingDimensions\x12\x14\n\x0c\x64\x65vice_ready\x18\x04 \x01(\x08\"G\n\x0c\x44\x65viceEvents\x12\x37\n\x06\x65vents\x18\x01 \x03(\x0b\x32\'.chromiumos.test.scheduling.DeviceEventB\tZ\x07./protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.test.scheduling.device_event_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./proto'
  _DEVICEEVENT.fields_by_name['pod_id']._options = None
  _DEVICEEVENT.fields_by_name['pod_id']._serialized_options = b'\030\001'
  _DEVICEEVENT._serialized_start=132
  _DEVICEEVENT._serialized_end=301
  _DEVICEEVENTS._serialized_start=303
  _DEVICEEVENTS._serialized_end=374
# @@protoc_insertion_point(module_scope)
