# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_platform/v2/summary.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etest_platform/v2/summary.proto\x12\x10test_platform.v2\"\"\n\x04Item\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"0\n\x07Summary\x12%\n\x05items\x18\x01 \x03(\x0b\x32\x16.test_platform.v2.Item\".\n\x05Items\x12%\n\x05items\x18\x01 \x03(\x0b\x32\x16.test_platform.v2.Item\"\x97\x01\n\nSummaryMap\x12>\n\tsummaries\x18\x01 \x03(\x0b\x32+.test_platform.v2.SummaryMap.SummariesEntry\x1aI\n\x0eSummariesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.test_platform.v2.Items:\x02\x38\x01\x42JZHgo.chromium.org/chromiumos/infra/proto/go/test_platform/v2;test_platformb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_platform.v2.summary_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZHgo.chromium.org/chromiumos/infra/proto/go/test_platform/v2;test_platform'
  _SUMMARYMAP_SUMMARIESENTRY._options = None
  _SUMMARYMAP_SUMMARIESENTRY._serialized_options = b'8\001'
  _globals['_ITEM']._serialized_start=52
  _globals['_ITEM']._serialized_end=86
  _globals['_SUMMARY']._serialized_start=88
  _globals['_SUMMARY']._serialized_end=136
  _globals['_ITEMS']._serialized_start=138
  _globals['_ITEMS']._serialized_end=184
  _globals['_SUMMARYMAP']._serialized_start=187
  _globals['_SUMMARYMAP']._serialized_end=338
  _globals['_SUMMARYMAP_SUMMARIESENTRY']._serialized_start=265
  _globals['_SUMMARYMAP_SUMMARIESENTRY']._serialized_end=338
# @@protoc_insertion_point(module_scope)
