# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/firmware_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n chromiumos/firmware_config.proto\x12\nchromiumos\"8\n\x12ModelSigningConfig\x12\x0e\n\x06key_id\x18\x01 \x01(\t\x12\x12\n\nbrand_code\x18\x02 \x01(\t\".\n\x0f\x46irmwareVersion\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x0e\n\x06sha256\x18\x02 \x01(\t\"t\n\x0e\x46irmwareConfig\x12\x30\n\x0bro_firmware\x18\x01 \x01(\x0b\x32\x1b.chromiumos.FirmwareVersion\x12\x30\n\x0brw_firmware\x18\x02 \x01(\x0b\x32\x1b.chromiumos.FirmwareVersion\"\xba\x01\n\x16\x46irmwareConfigForModel\x12\r\n\x05model\x18\x01 \x01(\t\x12/\n\x07signing\x18\x02 \x01(\x0b\x32\x1e.chromiumos.ModelSigningConfig\x12/\n\x0b\x61p_firmware\x18\x03 \x01(\x0b\x32\x1a.chromiumos.FirmwareConfig\x12/\n\x0b\x65\x63_firmware\x18\x04 \x01(\x0b\x32\x1a.chromiumos.FirmwareConfigBY\n!com.google.chrome.crosinfra.protoZ4go.chromium.org/chromiumos/infra/proto/go/chromiumosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chromiumos.firmware_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.google.chrome.crosinfra.protoZ4go.chromium.org/chromiumos/infra/proto/go/chromiumos'
  _globals['_MODELSIGNINGCONFIG']._serialized_start=48
  _globals['_MODELSIGNINGCONFIG']._serialized_end=104
  _globals['_FIRMWAREVERSION']._serialized_start=106
  _globals['_FIRMWAREVERSION']._serialized_end=152
  _globals['_FIRMWARECONFIG']._serialized_start=154
  _globals['_FIRMWARECONFIG']._serialized_end=270
  _globals['_FIRMWARECONFIGFORMODEL']._serialized_start=273
  _globals['_FIRMWARECONFIGFORMODEL']._serialized_end=459
# @@protoc_insertion_point(module_scope)
