# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/prebuilts_cloud.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromiumos/prebuilts_cloud.proto',
  package='chromiumos',
  syntax='proto3',
  serialized_options=b'\n!com.google.chrome.crosinfra.protoZ4go.chromium.org/chromiumos/infra/proto/go/chromiumos',
  serialized_pb=b'\n chromiumos/prebuilts_cloud.proto\x12\nchromiumos\x1a\x1fgoogle/protobuf/timestamp.proto\"q\n\x19UpdateSnapshotDataRequest\x12\x14\n\x0csnapshot_sha\x18\x01 \x01(\t\x12\x14\n\x0csnapshot_num\x18\x02 \x01(\r\x12\x10\n\x08\x65xternal\x18\x03 \x01(\x08\x12\x16\n\x0e\x62uildbucket_id\x18\x04 \x01(\x04\"\xba\x01\n\x18UpdateBinhostDataRequest\x12\x14\n\x0c\x62uild_target\x18\x01 \x01(\t\x12\x0f\n\x07profile\x18\x02 \x01(\t\x12\x14\n\x0csnapshot_sha\x18\x03 \x01(\t\x12\x0e\n\x06gs_uri\x18\x04 \x01(\t\x12\x16\n\x0egs_bucket_name\x18\x05 \x01(\t\x12\x16\n\x0e\x62uildbucket_id\x18\x06 \x01(\x04\x12\x10\n\x08\x63omplete\x18\x07 \x01(\x08\x12\x0f\n\x07private\x18\x08 \x01(\x08\"\xd9\x01\n\x15LookupBinhostsRequest\x12\x16\n\x0egs_bucket_name\x18\x01 \x01(\t\x12\x15\n\rsnapshot_shas\x18\x02 \x03(\t\x12\x14\n\x0c\x62uild_target\x18\x03 \x01(\t\x12\x0f\n\x07profile\x18\x04 \x01(\t\x12\x0f\n\x07private\x18\x05 \x01(\x08\x12\"\n\x1aget_corresponding_binhosts\x18\x06 \x01(\x08\x12\x1c\n\x14generic_build_target\x18\x07 \x01(\t\x12\x17\n\x0fgeneric_profile\x18\x08 \x01(\t\"\xb5\x01\n\x16LookupBinhostsResponse\x12<\n\x08\x62inhosts\x18\x01 \x03(\x0b\x32*.chromiumos.LookupBinhostsResponse.Binhost\x1a]\n\x07\x42inhost\x12\x12\n\nbinhost_id\x18\x01 \x01(\x04\x12\x0e\n\x06gs_uri\x18\x02 \x01(\t\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampBY\n!com.google.chrome.crosinfra.protoZ4go.chromium.org/chromiumos/infra/proto/go/chromiumosb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_UPDATESNAPSHOTDATAREQUEST = _descriptor.Descriptor(
  name='UpdateSnapshotDataRequest',
  full_name='chromiumos.UpdateSnapshotDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='snapshot_sha', full_name='chromiumos.UpdateSnapshotDataRequest.snapshot_sha', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='snapshot_num', full_name='chromiumos.UpdateSnapshotDataRequest.snapshot_num', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='external', full_name='chromiumos.UpdateSnapshotDataRequest.external', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buildbucket_id', full_name='chromiumos.UpdateSnapshotDataRequest.buildbucket_id', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=194,
)


_UPDATEBINHOSTDATAREQUEST = _descriptor.Descriptor(
  name='UpdateBinhostDataRequest',
  full_name='chromiumos.UpdateBinhostDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='build_target', full_name='chromiumos.UpdateBinhostDataRequest.build_target', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profile', full_name='chromiumos.UpdateBinhostDataRequest.profile', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='snapshot_sha', full_name='chromiumos.UpdateBinhostDataRequest.snapshot_sha', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gs_uri', full_name='chromiumos.UpdateBinhostDataRequest.gs_uri', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gs_bucket_name', full_name='chromiumos.UpdateBinhostDataRequest.gs_bucket_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buildbucket_id', full_name='chromiumos.UpdateBinhostDataRequest.buildbucket_id', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='complete', full_name='chromiumos.UpdateBinhostDataRequest.complete', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='private', full_name='chromiumos.UpdateBinhostDataRequest.private', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=383,
)


_LOOKUPBINHOSTSREQUEST = _descriptor.Descriptor(
  name='LookupBinhostsRequest',
  full_name='chromiumos.LookupBinhostsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gs_bucket_name', full_name='chromiumos.LookupBinhostsRequest.gs_bucket_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='snapshot_shas', full_name='chromiumos.LookupBinhostsRequest.snapshot_shas', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_target', full_name='chromiumos.LookupBinhostsRequest.build_target', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profile', full_name='chromiumos.LookupBinhostsRequest.profile', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='private', full_name='chromiumos.LookupBinhostsRequest.private', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='get_corresponding_binhosts', full_name='chromiumos.LookupBinhostsRequest.get_corresponding_binhosts', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='generic_build_target', full_name='chromiumos.LookupBinhostsRequest.generic_build_target', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='generic_profile', full_name='chromiumos.LookupBinhostsRequest.generic_profile', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=603,
)


_LOOKUPBINHOSTSRESPONSE_BINHOST = _descriptor.Descriptor(
  name='Binhost',
  full_name='chromiumos.LookupBinhostsResponse.Binhost',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='binhost_id', full_name='chromiumos.LookupBinhostsResponse.Binhost.binhost_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gs_uri', full_name='chromiumos.LookupBinhostsResponse.Binhost.gs_uri', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='chromiumos.LookupBinhostsResponse.Binhost.created_at', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=694,
  serialized_end=787,
)

_LOOKUPBINHOSTSRESPONSE = _descriptor.Descriptor(
  name='LookupBinhostsResponse',
  full_name='chromiumos.LookupBinhostsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='binhosts', full_name='chromiumos.LookupBinhostsResponse.binhosts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LOOKUPBINHOSTSRESPONSE_BINHOST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=606,
  serialized_end=787,
)

_LOOKUPBINHOSTSRESPONSE_BINHOST.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_LOOKUPBINHOSTSRESPONSE_BINHOST.containing_type = _LOOKUPBINHOSTSRESPONSE
_LOOKUPBINHOSTSRESPONSE.fields_by_name['binhosts'].message_type = _LOOKUPBINHOSTSRESPONSE_BINHOST
DESCRIPTOR.message_types_by_name['UpdateSnapshotDataRequest'] = _UPDATESNAPSHOTDATAREQUEST
DESCRIPTOR.message_types_by_name['UpdateBinhostDataRequest'] = _UPDATEBINHOSTDATAREQUEST
DESCRIPTOR.message_types_by_name['LookupBinhostsRequest'] = _LOOKUPBINHOSTSREQUEST
DESCRIPTOR.message_types_by_name['LookupBinhostsResponse'] = _LOOKUPBINHOSTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateSnapshotDataRequest = _reflection.GeneratedProtocolMessageType('UpdateSnapshotDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESNAPSHOTDATAREQUEST,
  '__module__' : 'chromiumos.prebuilts_cloud_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.UpdateSnapshotDataRequest)
  })
_sym_db.RegisterMessage(UpdateSnapshotDataRequest)

UpdateBinhostDataRequest = _reflection.GeneratedProtocolMessageType('UpdateBinhostDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEBINHOSTDATAREQUEST,
  '__module__' : 'chromiumos.prebuilts_cloud_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.UpdateBinhostDataRequest)
  })
_sym_db.RegisterMessage(UpdateBinhostDataRequest)

LookupBinhostsRequest = _reflection.GeneratedProtocolMessageType('LookupBinhostsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOOKUPBINHOSTSREQUEST,
  '__module__' : 'chromiumos.prebuilts_cloud_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.LookupBinhostsRequest)
  })
_sym_db.RegisterMessage(LookupBinhostsRequest)

LookupBinhostsResponse = _reflection.GeneratedProtocolMessageType('LookupBinhostsResponse', (_message.Message,), {

  'Binhost' : _reflection.GeneratedProtocolMessageType('Binhost', (_message.Message,), {
    'DESCRIPTOR' : _LOOKUPBINHOSTSRESPONSE_BINHOST,
    '__module__' : 'chromiumos.prebuilts_cloud_pb2'
    # @@protoc_insertion_point(class_scope:chromiumos.LookupBinhostsResponse.Binhost)
    })
  ,
  'DESCRIPTOR' : _LOOKUPBINHOSTSRESPONSE,
  '__module__' : 'chromiumos.prebuilts_cloud_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.LookupBinhostsResponse)
  })
_sym_db.RegisterMessage(LookupBinhostsResponse)
_sym_db.RegisterMessage(LookupBinhostsResponse.Binhost)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
