# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromiumos/signing.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.api.gen_sdk.chromiumos import common_pb2 as chromiumos_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chromiumos/signing.proto',
  package='chromiumos',
  syntax='proto3',
  serialized_options=b'\n!com.google.chrome.crosinfra.protoZ4go.chromium.org/chromiumos/infra/proto/go/chromiumos',
  serialized_pb=b'\n\x18\x63hromiumos/signing.proto\x12\nchromiumos\x1a\x17\x63hromiumos/common.proto\"\xec\x01\n\rSigningConfig\x12\x14\n\x0c\x64isplay_name\x18\x01 \x01(\t\x12\x0e\n\x06keyset\x18\x02 \x01(\t\x12)\n\nimage_type\x18\x03 \x01(\x0e\x32\x15.chromiumos.ImageType\x12\x14\n\x0crecovery_zip\x18\x04 \x01(\x08\x12\x1a\n\x12\x65nsure_no_password\x18\x05 \x01(\x08\x12\x17\n\x0f\x66irmware_update\x18\x06 \x01(\x08\x12\x13\n\x0binput_files\x18\x07 \x03(\t\x12\x14\n\x0coutput_names\x18\x08 \x03(\t\x12\x14\n\x0c\x61rchive_path\x18\t \x01(\t\"d\n\x18\x42uildTargetSigningConfig\x12\x14\n\x0c\x62uild_target\x18\x01 \x01(\t\x12\x32\n\x0fsigning_configs\x18\x02 \x03(\x0b\x32\x19.chromiumos.SigningConfig\"g\n\x19\x42uildTargetSigningConfigs\x12J\n\x1c\x62uild_target_signing_configs\x18\x01 \x03(\x0b\x32$.chromiumos.BuildTargetSigningConfigBY\n!com.google.chrome.crosinfra.protoZ4go.chromium.org/chromiumos/infra/proto/go/chromiumosb\x06proto3'
  ,
  dependencies=[chromiumos_dot_common__pb2.DESCRIPTOR,])




_SIGNINGCONFIG = _descriptor.Descriptor(
  name='SigningConfig',
  full_name='chromiumos.SigningConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='display_name', full_name='chromiumos.SigningConfig.display_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keyset', full_name='chromiumos.SigningConfig.keyset', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_type', full_name='chromiumos.SigningConfig.image_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recovery_zip', full_name='chromiumos.SigningConfig.recovery_zip', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ensure_no_password', full_name='chromiumos.SigningConfig.ensure_no_password', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='firmware_update', full_name='chromiumos.SigningConfig.firmware_update', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_files', full_name='chromiumos.SigningConfig.input_files', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_names', full_name='chromiumos.SigningConfig.output_names', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='archive_path', full_name='chromiumos.SigningConfig.archive_path', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=302,
)


_BUILDTARGETSIGNINGCONFIG = _descriptor.Descriptor(
  name='BuildTargetSigningConfig',
  full_name='chromiumos.BuildTargetSigningConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='build_target', full_name='chromiumos.BuildTargetSigningConfig.build_target', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signing_configs', full_name='chromiumos.BuildTargetSigningConfig.signing_configs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=404,
)


_BUILDTARGETSIGNINGCONFIGS = _descriptor.Descriptor(
  name='BuildTargetSigningConfigs',
  full_name='chromiumos.BuildTargetSigningConfigs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='build_target_signing_configs', full_name='chromiumos.BuildTargetSigningConfigs.build_target_signing_configs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=509,
)

_SIGNINGCONFIG.fields_by_name['image_type'].enum_type = chromiumos_dot_common__pb2._IMAGETYPE
_BUILDTARGETSIGNINGCONFIG.fields_by_name['signing_configs'].message_type = _SIGNINGCONFIG
_BUILDTARGETSIGNINGCONFIGS.fields_by_name['build_target_signing_configs'].message_type = _BUILDTARGETSIGNINGCONFIG
DESCRIPTOR.message_types_by_name['SigningConfig'] = _SIGNINGCONFIG
DESCRIPTOR.message_types_by_name['BuildTargetSigningConfig'] = _BUILDTARGETSIGNINGCONFIG
DESCRIPTOR.message_types_by_name['BuildTargetSigningConfigs'] = _BUILDTARGETSIGNINGCONFIGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SigningConfig = _reflection.GeneratedProtocolMessageType('SigningConfig', (_message.Message,), {
  'DESCRIPTOR' : _SIGNINGCONFIG,
  '__module__' : 'chromiumos.signing_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.SigningConfig)
  })
_sym_db.RegisterMessage(SigningConfig)

BuildTargetSigningConfig = _reflection.GeneratedProtocolMessageType('BuildTargetSigningConfig', (_message.Message,), {
  'DESCRIPTOR' : _BUILDTARGETSIGNINGCONFIG,
  '__module__' : 'chromiumos.signing_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.BuildTargetSigningConfig)
  })
_sym_db.RegisterMessage(BuildTargetSigningConfig)

BuildTargetSigningConfigs = _reflection.GeneratedProtocolMessageType('BuildTargetSigningConfigs', (_message.Message,), {
  'DESCRIPTOR' : _BUILDTARGETSIGNINGCONFIGS,
  '__module__' : 'chromiumos.signing_pb2'
  # @@protoc_insertion_point(class_scope:chromiumos.BuildTargetSigningConfigs)
  })
_sym_db.RegisterMessage(BuildTargetSigningConfigs)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
