#!/bin/bash
# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# rust-analyzer was moved into rust-host in b/323319198.
# Since blockers require new prebuilts, which is relatively high-overhead for
# Rust toolchain packages, just use a hook to clean it up.
set -u

equery --quiet l 'sys-apps/rust-analyzer'
exit_code="$?"
case "${exit_code}" in
  0 )
    sudo emerge --rage-clean 'sys-apps/rust-analyzer'
    ;;

  # `equery` will exit with 3 if it completed successfully but found no matches.
  3 )
    exit 0
    ;;

  * )
    exit "${exit_code}"
    ;;
esac
