# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from chromite.third_party.google.protobuf.internal import builder as _builder
from chromite.third_party.google.protobuf import descriptor as _descriptor
from chromite.third_party.google.protobuf import descriptor_pool as _descriptor_pool
from chromite.third_party.google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromite.third_party.google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04test\x1a\x1bgoogle/protobuf/empty.proto\"\x18\n\x0bGiveRequest\x12\t\n\x01m\x18\x01 \x01(\x03\"\x19\n\x0cTakeResponse\x12\t\n\x01k\x18\x01 \x01(\x03\"+\n\x0b\x45\x63hoRequest\x12\x1c\n\x01r\x18\x01 \x01(\x0b\x32\x11.test.GiveRequest\" \n\x0c\x45\x63hoResponse\x12\x10\n\x08response\x18\x01 \x03(\t2\xa2\x01\n\x04Test\x12\x33\n\x04Give\x12\x11.test.GiveRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x34\n\x04Take\x12\x16.google.protobuf.Empty\x1a\x12.test.TakeResponse\"\x00\x12/\n\x04\x45\x63ho\x12\x11.test.EchoRequest\x1a\x12.test.EchoResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GIVEREQUEST._serialized_start=49
  _GIVEREQUEST._serialized_end=73
  _TAKERESPONSE._serialized_start=75
  _TAKERESPONSE._serialized_end=100
  _ECHOREQUEST._serialized_start=102
  _ECHOREQUEST._serialized_end=145
  _ECHORESPONSE._serialized_start=147
  _ECHORESPONSE._serialized_end=179
  _TEST._serialized_start=182
  _TEST._serialized_end=344
# @@protoc_insertion_point(module_scope)
